name: ci
on:
  push:
    branches:
      - '*'
jobs:
  build-linux:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: sudo apt update -yqq && sudo apt install -yqq ninja-build xorg-dev
      - name: configure gcc
        run: cmake -S . --preset=default -B build -DBAVE_BUILD_SHADERS=OFF -DBAVE_USE_FREETYPE=OFF -DCAPO_USE_OPENAL=OFF
      - name: configure clang
        run: cmake -S . --preset=ninja-clang -B clang -DBAVE_BUILD_SHADERS=OFF -DBAVE_USE_FREETYPE=OFF -DCAPO_USE_OPENAL=OFF
      - name: build gcc
        run: cmake --build build --config=Release -- -d explain
      - name: build clang
        run: cmake --build clang --config=Release
      - name: test
        run: cd build && ctest -C Release
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: configure
        run: cmake -S . --preset=vs22 -B build -DBAVE_BUILD_SHADERS=OFF -DBAVE_USE_FREETYPE=OFF -DCAPO_USE_OPENAL=OFF
      - name: build
        run: cmake --build build --config=Release
      - name: test
        run: cd build && ctest -C Release
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: init
        run: brew install ninja
      - name: configure
        run: cmake -S . --preset=default -B build -DBAVE_BUILD_SHADERS=OFF -DBAVE_USE_FREETYPE=OFF -DCAPO_USE_OPENAL=OFF
      - name: build
        run: cmake --build build --config=Release -- -d explain
      - name: test
        run: cd build && ctest -C Release
